"""kdjhasgd

Revision ID: c41baf7977f5
Revises: 
Create Date: 2022-08-30 23:57:02.000740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c41baf7977f5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('professional',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=64), nullable=True),
    sa.Column('calendly_url', sa.String(length=64), nullable=True),
    sa.Column('skill_level', sa.String(length=64), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('bio', sa.String(length=64), nullable=True),
    sa.Column('specialization', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_professional_bio'), 'professional', ['bio'], unique=False)
    op.create_index(op.f('ix_professional_calendly_url'), 'professional', ['calendly_url'], unique=False)
    op.create_index(op.f('ix_professional_category'), 'professional', ['category'], unique=False)
    op.create_index(op.f('ix_professional_email'), 'professional', ['email'], unique=True)
    op.create_index(op.f('ix_professional_password_hash'), 'professional', ['password_hash'], unique=False)
    op.create_index(op.f('ix_professional_skill_level'), 'professional', ['skill_level'], unique=False)
    op.create_index(op.f('ix_professional_specialization'), 'professional', ['specialization'], unique=False)
    op.create_index(op.f('ix_professional_username'), 'professional', ['username'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=64), nullable=True),
    sa.Column('image_url', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_image_url'), 'users', ['image_url'], unique=False)
    op.create_index(op.f('ix_users_password_hash'), 'users', ['password_hash'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_password_hash'), table_name='users')
    op.drop_index(op.f('ix_users_image_url'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_professional_username'), table_name='professional')
    op.drop_index(op.f('ix_professional_specialization'), table_name='professional')
    op.drop_index(op.f('ix_professional_skill_level'), table_name='professional')
    op.drop_index(op.f('ix_professional_password_hash'), table_name='professional')
    op.drop_index(op.f('ix_professional_email'), table_name='professional')
    op.drop_index(op.f('ix_professional_category'), table_name='professional')
    op.drop_index(op.f('ix_professional_calendly_url'), table_name='professional')
    op.drop_index(op.f('ix_professional_bio'), table_name='professional')
    op.drop_table('professional')
    # ### end Alembic commands ###
